### ISSUE TITLE
[Chore]: Automate the generation of .spashiprc.yml

### ISSUE THREAD

**Issue by ghanlohar** [spaship/spaship#1252]
## Is your chore related to a problem? Please describe:

As of we generate the .spashiprc.yml manually with the environment details & API keys,

It's been observed that if we miss on the formatting, SPAship doesn't recognize the yml.

## Describe the solution you'd like:

So if we can automate .spashiprc.yml, SPAship will take away the responsibility & reduce the chances of manual format errors.
## Describe alternatives you've considered:

Manually check on yml formatting for any potential formating issues.

**Comment by mwcz** [comment]
There's definitely a need to streamline creation of spashiprc.  However, the CLI doesn't have access to the information required to populate spashiprc, but the UI does.  That's why the existing issues (#509 and #893) related to this topic suggests making a copy-pastable spashiprc template in SPAship Manager.
