### ISSUE TITLE
[manager] redirect loop

### ISSUE THREAD

**Issue by kunyan** [spaship/spaship#237]
There are some keycloak config make the privateRoute assume it is not login. then redirect to login page. but it will be auto login again.

**Comment by kunyan** [comment]
it looks only happened in my local, the site in OpenShift not have this problem

**Comment by kunyan** [comment]
I tried `Safari` and `Chrome`. the issue still present。
Is there any changes in SSO side ? some strict policy for `localhost` ? @mwcz

**Comment by kunyan** [comment]
The issue located at the `loginiFrame`. the check login state will trigger the `onAuthLogout`. it will redirect the page to `/login`.


a workaround for local development:


Set `checkLoginIframeInterval`, default value is 5 sec.
```
<KeycloakProvider
      keycloak={keycloak}
      initConfig={{ onLoad: "login-required", checkLoginIframeInterval: 60 }}
      onTokens={(...tokens) => console.log("KeycloakProvider onToken:", tokens)}
      onEvent={(event, error) => console.log("KeycloakProvider onEvent:", event, error)}
    >
      <AppRouter />
    </KeycloakProvider>
```

**Comment by npatil9** [comment]
Similar issue happend in One Portal. @sayak-sarkar to work with @kunyan

**Comment by sayak-sarkar** [comment]
Hey @kunyan I'm unable to reproduce this issue on my local. Is there some env where I can inspect this issue?

**Comment by kunyan** [comment]
Interesting. I can not reproduce this issue any more :)

**Comment by mwcz** [comment]
I just remembered that I once saw a strange redirect loop on the Customer Portal.  It was in one of my team members' browsers, and turned out the issue was that the calculated `timeSkew` (the clock difference between the browser and keycloak server) was huge.  It's normally less than 1s, but in this case it was much larger, hours maybe or even days.  I'm not sure how the timeSkew got into that state, but the result is that every token issued was immediately expired, causing each new pageview to trigger a login.  Hence, the redirect loop.

Maybe that's what happened.
