### ISSUE TITLE
Only run automated github code maintenance processes once per week

### ISSUE THREAD

**Issue by Jared-Sprague** [spaship/spaship#55]
Tools like Renevate are making it hard to see actual daily update notifications of commits etc by our team across geos because of all they get buried in all the auto-process notifications.

We should try to run these on a weekly schedule, not daily.

**Comment by mwcz** [comment]
I like it.  Let's run it on the weekend so we have a set of renovate PRs to tackle at the beginning of each week.

This probably won't give us fewer PRs, but at least they won't be popping up throughout the week while we're trying to focus on other stuff.

**Comment by mwcz** [comment]
Also, Sayak and I discussed the possibility of having renovate batch updates into a single PR.  I wasn't able to find a renovate setting to do that.  If there is one, we can consider it.  I am not completely convinced because there is one major downside: if a batch of dependency updates breaks things, it becomes much harder to figure out which dependency is the root cause.

**Comment by mwcz** [comment]
```
"schedule": "every weekend"
```

I love renovate.
